### ISSUE TITLE
Getting Session Array Blank

### ISSUE THREAD

**Issue by JustBeDigital** [amabnl/amadeus-ws-client#85] opened 2017-07-21 15:26 UTC
Hello,

I am trying to test the FareMasterPricerTbSearch then i am getting Fault Status with host could not reach. I also try to print the Client response but in this case their is no value coming in sessionId, sequenceNumber, securityToken while when i test through https://webservices.amadeus.com then i get the sessions details. For more please find the below code:

$params = new Params([
        'authParams' => [
            'officeId' => 'XXX', //Office Id
            'userId' => 'XXX', //UserId
            'passwordData' =>'XXX', // **base 64 encoded** password
            'passwordLength' => 8,
            'dutyCode' => 'XX', // duty code
            'organizationId' => 'XX', //Organization Id
        ],
        'sessionHandlerParams' => [
            'soapHeaderVersion' => Client::HEADER_V2,
            'wsdl' => '', //path of the wsdl file
	     'stateful' => true,
            'logger' => new Psr\Log\NullLogger(),
	   ],
        'requestCreatorParams' => [
            'receivedFrom' => 'My Project' 
        ]
    ]);
	 $client = new Client($params); 

In the above code when i try to print the $client then i get sessionData array with blank values in sessionId, sequenceNumber, securityToken.

Secondly i want to know how i debug (print) the request in XML format i try to enable the returnXml=true by default but still the same.

**Comment by DerMika** [comment] 2017-07-24 15:20
Hi, sorry for the late response, I'm on holiday. 

I see you're using SoapHeader 2. That implementation requires you to manually send an authenticate message before performing any other action. This is the reason for the blank session.

You can use the `getLastRequest()` and `getLastResponse()` methods on the client to get the request and response messages raw XML.

**Comment by JustBeDigital** [comment] 2017-07-24 17:11
Hi DerMika,

Thanks for the reply,

I try to print the request and response through getLastRequest() and getLastResponse() but i still get blank in both cases.

And when i try to call fareMasterPricerTravelBoardSearch then the below message coming
[0] => Amadeus\Client\Result\NotOk Object
                (
                    [code] => Could not connect to host
                    [text] => 
                    [level] => 
                )

Please help me in both cases.

Thanks 
JustBeDigital

**Comment by DerMika** [comment] 2017-07-24 18:05
If you can't connect to the server, you won't be sending any messages, so that would explain why you'd get a blank response.

Question is why can't you connect, have you tested if you can reach the Amadeus server endpoint in your WSDL? This is not something I can help you with, sounds like a WSDL issue or a network issue.

**Comment by JustBeDigital** [comment] 2017-07-24 19:14
Hello,
I get could not connect to the server when I try to hit faretravelboardsearch but when I just call new client with passing params then it that case I didn't get sessions. 
While I test on webservices.amadeus.com then I receive a session details in response.

**Comment by JustBeDigital** [comment] 2017-07-25 14:41
Hi Dermika,
any update on above request.
I am waiting your kind response.

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-07-25 14:46
The client just uses connection data present in the WSDL. You will have to check in the WSDL what the endpoint is for this message, and then check your network connection yourself. There is nothing I can do to help you.

Have you tried the `securityAuthenticate ()` method? Does that work? Do you get session data after calling that method? If so, do a MasterPricer message after that and there is no reason it wouldn't work.

**Comment by JustBeDigital** [comment] 2017-07-25 16:46
Hi Der Mika,
please check below mentioned code and point out where we are wrong.
   use Amadeus\Client;
    use Amadeus\Client\Params;
    use Amadeus\Client\SoapClient;
    use Amadeus\Client\Result;
    use Amadeus\Client\RequestOptions\PnrRetrieveOptions;
	use Amadeus\Client\RequestOptions\FareMasterPricerTbSearch;
    use Amadeus\Client\RequestOptions\Fare\MPItinerary;
    use Amadeus\Client\RequestOptions\Fare\MPLocation;
    use Amadeus\Client\RequestOptions\Fare\MPPassenger;
    use Amadeus\Client\RequestOptions\Fare\MPDate;
$password=PasswordAmadeus; //get the password from the config
$OfficeID=OfficeIdAmadeus; //get the officeId from config
$username=UsernameAmadeus; //get the username from config
date_default_timezone_set("UTC"); 
$t = microtime(true); 
$micro = sprintf("%03d",($t - floor($t)) * 1000); 
$date = new DateTime( date('Y-m-d H:i:s.'.$micro) ); 
$timestamp = $date->format("Y-m-d\TH:i:s:").$micro . 'Z'; 
//$encodedNonce = base64_encode($nonce);
$nonce=base64_decode($encodedNonce);
$passSHA = base64_encode(sha1($nonce . $timestamp . sha1($password, true), true));

     $params = new Params([
        'authParams' => [
            'officeId' => $OfficeID, //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
            'userId' => $username, //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
            'passwordData' => $passSHA, // **base 64 encoded** password
			
			
        ],
        'sessionHandlerParams' => [
            'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
            'wsdl' => URL.'Amadeus_wsdl_lib/1ASIWSMLLVN_PDT_20170724_131430.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
            'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
            'logger' => new Psr\Log\NullLogger()
        ],
        'requestCreatorParams' => [
            'receivedFrom' => 'smartlinetravels project' // The "Received From" string that will be visible in PNR History
        ],
		'returnXml' => true
    ]);  

	
	//print_r($params); die;
     $client = new Client($params); 

	/* echo "<textarea>";
	print_r($client->getLastRequest()); 
	echo "</textarea>"; 
	die; */
	echo "<pre>";
	print_r($client->securityAuthenticate());die; 

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-07-25 16:56
You do not need to perform all these operations on the password. The client needs the base_64 encoded version of the plain text password and it will do all the sha1 operations to pass the correct password.

**Comment by JustBeDigital** [comment] 2017-07-25 17:04
Hi Der Mika,
I have done as per your guideline but still same.
please check below mentioned code.
I am waiting your kind response.

use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\SoapClient;
use Amadeus\Client\Result;
use Amadeus\Client\RequestOptions\PnrRetrieveOptions;
use Amadeus\Client\RequestOptions\FareMasterPricerTbSearch;
use Amadeus\Client\RequestOptions\Fare\MPItinerary;
use Amadeus\Client\RequestOptions\Fare\MPLocation;
use Amadeus\Client\RequestOptions\Fare\MPPassenger;
use Amadeus\Client\RequestOptions\Fare\MPDate;
	

$password=PasswordAmadeus; //get the password from the config
$OfficeID=OfficeIdAmadeus; //get the officeId from config
$username=UsernameAmadeus; //get the username from config


     $params = new Params([
        'authParams' => [
            'officeId' => $OfficeID, //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
            'userId' => $username, //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
            'passwordData' => base64_encode($password), // **base 64 encoded** password
			
			
        ],
        'sessionHandlerParams' => [
            'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
            'wsdl' => URL.'Amadeus_wsdl_lib/1ASIWSMLLVN_PDT_20170724_131430.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
            'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
            'logger' => new Psr\Log\NullLogger()
        ],
        'requestCreatorParams' => [
            'receivedFrom' => 'smartlinetravels project' // The "Received From" string that will be visible in PNR History
        ],
		'returnXml' => true
    ]);  

	
     $client = new Client($params); 

	echo "<pre>";
	print_r($client->securityAuthenticate());die; 

Regards,
-Kunwar Ali

**Comment by JustBeDigital** [comment] 2017-07-25 17:06
Hi Der Mika,
below is the response of above code.

Amadeus\Client Object
(
    [lastMessage:protected] => 
    [sessionHandler:protected] => Amadeus\Client\Session\Handler\SoapHeader4 Object
        (
            [isStateful:protected] => 
            [hasContext:protected] => 
            [context:protected] => 
            [sessionData:protected] => Array
                (
                    [sessionId] => 
                    [sequenceNumber] => 
                    [securityToken] => 
                )

            [isAuthenticated:protected] => 
            [soapClients:protected] => Array
                (
                )

            [soapClientOptions:protected] => Array
                (
                    [trace] => 1
                    [exceptions] => 1
                    [soap_version] => 1
                )

            [params:protected] => Amadeus\Client\Params\SessionHandlerParams Object
                (
                    [wsdl] => Array
                        (
                            [0] => http://10.10.10.92/smartlinetravels/Amadeus_wsdl_lib/1ASIWSMLLVN_PDT_20170724_131430.wsdl
                        )

                    [soapHeaderVersion] => 4
                    [authParams] => Amadeus\Client\Params\AuthParams Object
                        (
                            [officeId] => BDR1S2104
                            [originatorTypeCode] => U
                            [dutyCode] => SU
                            [userId] => WSLVNSML
                            [organizationId] => 
                            [passwordLength] => 
                            [passwordData] => QU1BV0VCMTgyNA==
                            [nonceBase] => qxMbO0P8VLPYhcbWitKkvC
                        )

                    [stateful] => 
                    [logger] => Psr\Log\NullLogger Object
                        (
                        )

                    [soapClientOptions] => Array
                        (
                        )

                    [overrideSoapClient] => 
                    [overrideSoapClientWsdlName] => 
                )

            [messagesAndVersions:protected] => Array
                (
                    [Air_RebookAirSegment] => Array
                        (
                            [version] => 14.1
                            [wsdl] => b550adae
                        )

                    [Air_SellFromRecommendation] => Array
                        (
                            [version] => 5.2
                            [wsdl] => b550adae
                        )

                    [Command_Cryptic] => Array
                        (
                            [version] => 7.3
                            [wsdl] => b550adae
                        )

                    [DocIssuance_IssueTicket] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [FOP_CreateFormOfPayment] => Array
                        (
                            [version] => 15.4
                            [wsdl] => b550adae
                        )

                    [Fare_InformativeBestPricingWithoutPNR] => Array
                        (
                            [version] => 14.1
                            [wsdl] => b550adae
                        )

                    [Fare_MasterPricerTravelBoardSearch] => Array
                        (
                            [version] => 14.3
                            [wsdl] => b550adae
                        )

                    [Fare_PricePNRWithBookingClass] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [Fare_PricePNRWithLowerFares] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [PNR_AddFrequentFlyer] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                    [PNR_AddMultiElements] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [PNR_Retrieve] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [Security_Authenticate] => Array
                        (
                            [version] => 6.1
                            [wsdl] => b550adae
                        )

                    [Security_SignOut] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                    [Ticket_CreateTSTFromPricing] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                    [Ticket_DeleteTST] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                )

            [logger:protected] => Psr\Log\NullLogger Object
                (
                )

        )

    [requestCreator:protected] => Amadeus\Client\RequestCreator\Base Object
        (
            [params:protected] => Amadeus\Client\Params\RequestCreatorParams Object
                (
                    [originatorOfficeId] => BDR1S2104
                    [receivedFrom] => smartlinetravels project Supportmart Amadeus-1.5.0-dev
                    [messagesAndVersions] => Array
                        (
                            [Air_RebookAirSegment] => Array
                                (
                                    [version] => 14.1
                                    [wsdl] => b550adae
                                )

                            [Air_SellFromRecommendation] => Array
                                (
                                    [version] => 5.2
                                    [wsdl] => b550adae
                                )

                            [Command_Cryptic] => Array
                                (
                                    [version] => 7.3
                                    [wsdl] => b550adae
                                )

                            [DocIssuance_IssueTicket] => Array
                                (
                                    [version] => 15.1
                                    [wsdl] => b550adae
                                )

                            [FOP_CreateFormOfPayment] => Array
                                (
                                    [version] => 15.4
                                    [wsdl] => b550adae
                                )

                            [Fare_InformativeBestPricingWithoutPNR] => Array
                                (
                                    [version] => 14.1
                                    [wsdl] => b550adae
                                )

                            [Fare_MasterPricerTravelBoardSearch] => Array
                                (
                                    [version] => 14.3
                                    [wsdl] => b550adae
                                )

                            [Fare_PricePNRWithBookingClass] => Array
                                (
                                    [version] => 15.1
                                    [wsdl] => b550adae
                                )

                            [Fare_PricePNRWithLowerFares] => Array
                                (
                                    [version] => 15.1
                                    [wsdl] => b550adae
                                )

                            [PNR_AddFrequentFlyer] => Array
                                (
                                    [version] => 4.1
                                    [wsdl] => b550adae
                                )

                            [PNR_AddMultiElements] => Array
                                (
                                    [version] => 15.1
                                    [wsdl] => b550adae
                                )

                            [PNR_Retrieve] => Array
                                (
                                    [version] => 15.1
                                    [wsdl] => b550adae
                                )

                            [Security_Authenticate] => Array
                                (
                                    [version] => 6.1
                                    [wsdl] => b550adae
                                )

                            [Security_SignOut] => Array
                                (
                                    [version] => 4.1
                                    [wsdl] => b550adae
                                )

                            [Ticket_CreateTSTFromPricing] => Array
                                (
                                    [version] => 4.1
                                    [wsdl] => b550adae
                                )

                            [Ticket_DeleteTST] => Array
                                (
                                    [version] => 4.1
                                    [wsdl] => b550adae
                                )

                        )

                )

            [messagesAndVersions:protected] => Array
                (
                    [Air_RebookAirSegment] => Array
                        (
                            [version] => 14.1
                            [wsdl] => b550adae
                        )

                    [Air_SellFromRecommendation] => Array
                        (
                            [version] => 5.2
                            [wsdl] => b550adae
                        )

                    [Command_Cryptic] => Array
                        (
                            [version] => 7.3
                            [wsdl] => b550adae
                        )

                    [DocIssuance_IssueTicket] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [FOP_CreateFormOfPayment] => Array
                        (
                            [version] => 15.4
                            [wsdl] => b550adae
                        )

                    [Fare_InformativeBestPricingWithoutPNR] => Array
                        (
                            [version] => 14.1
                            [wsdl] => b550adae
                        )

                    [Fare_MasterPricerTravelBoardSearch] => Array
                        (
                            [version] => 14.3
                            [wsdl] => b550adae
                        )

                    [Fare_PricePNRWithBookingClass] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [Fare_PricePNRWithLowerFares] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [PNR_AddFrequentFlyer] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                    [PNR_AddMultiElements] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [PNR_Retrieve] => Array
                        (
                            [version] => 15.1
                            [wsdl] => b550adae
                        )

                    [Security_Authenticate] => Array
                        (
                            [version] => 6.1
                            [wsdl] => b550adae
                        )

                    [Security_SignOut] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                    [Ticket_CreateTSTFromPricing] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                    [Ticket_DeleteTST] => Array
                        (
                            [version] => 4.1
                            [wsdl] => b550adae
                        )

                )

            [messageBuilders:protected] => Array
                (
                )

        )

    [responseHandler:protected] => Amadeus\Client\ResponseHandler\Base Object
        (
            [responseHandlers:protected] => Array
                (
                )

        )

    [authParams:protected] => Amadeus\Client\Params\AuthParams Object
        (
            [officeId] => BDR1S2104
            [originatorTypeCode] => U
            [dutyCode] => SU
            [userId] => WSLVNSML
            [organizationId] => 
            [passwordLength] => 
            [passwordData] => QU1BV0VCMTgyNA==
            [nonceBase] => qxMbO0P8VLPYhcbWitKkvC
        )

    [returnResultXml:protected] => 1
)

Regards,
-kunwar Ali

**Comment by JustBeDigital** [comment] 2017-07-25 17:54
Hi Der Mika,

any update on above request.
I am waiting your kind response.

Regards,
-Kunwar Ali

**Comment by JustBeDigital** [comment] 2017-07-26 14:48
Hi Der Mika,

any update on above request.

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-10 07:30
Hi, I'm sorry but I was unavailable for a while.

Have you been able to figure out the problem in the mean time? 

some questions that popped up: 

- what is your objective, trying to authenticate?
- which soapheader version is your WSAP using? You seem to be using SoapHeader 4 which does not require a separate Authenticate message. The library will authenticate you when you send your first message.
- I see you're using the dev-master version, I suggest you use a released version (install as composer dependency as explained in the docs). 
- please do not post your password to the entire world ;) (I've edited it out)

**Comment by JustBeDigital** [comment] 2017-08-15 17:10
Hi DerMika ,

Thanks fore update.
can you please provide me released version link.
I am waiting your kind response.
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-15 17:14
Just follow the installation instructions from [the readme](https://github.com/amabnl/amadeus-ws-client/blob/master/README.md#installation) and you should have the latest version 1.4.0.

**Comment by JustBeDigital** [comment] 2017-08-16 17:54
Hi DerMika,
I have download amadeus ws client from https://github.com/amabnl/amadeus-ws-client..
I have install composer as per your guidelines.
But I am facing same Issues.
**below are the response** 
Amadeus\Client\Result Object
(
    [status] => FATAL
    [messages] => Array
        (
            [0] => Amadeus\Client\Result\NotOk Object
                (
                    [code] => Could not connect to host
                    [text] => 
                    [level] => 
                )

        )

    [response] => 
    [responseXml] => 
)
**Please check the screenshot for directory structure.**
![eroor](https://user-images.githubusercontent.com/30349487/29377262-eb72939c-82d8-11e7-9850-855021661316.png)
please check the below code for my_try.php file which is red marked in attached screenshot

include_once('vendor/autoload.php');

use Amadeus\Client;
use Amadeus\Client\Params;
use Amadeus\Client\Result;
use Amadeus\Client\RequestOptions\FareMasterPricerTbSearch;
use Amadeus\Client\RequestOptions\Fare\MPItinerary;
use Amadeus\Client\RequestOptions\Fare\MPLocation;
 use Amadeus\Client\RequestOptions\Fare\MPPassenger;
use Amadeus\Client\RequestOptions\Fare\MPDate;
//Set up the client with necessary parameters:

$params = new Params([
    'authParams' => [
        'officeId' => 'xxxxx', //The Amadeus Office Id you want to sign in to - must be open on your WSAP.
        'userId' => 'xxxx', //Also known as 'Originator' for Soap Header 1 & 2 WSDL's
        'passwordData' => base64_encode('yyyyy') // **base 64 encoded** password
    ],
    'sessionHandlerParams' => [
        'soapHeaderVersion' => Client::HEADER_V4, //This is the default value, can be omitted.
        'wsdl' => 'Amadeus_wsdl_lib/1ASIWSMLLVN_PDT_20170724_131430.wsdl', //Points to the location of the WSDL file for your WSAP. Make sure the associated XSD's are also available.
        'stateful' => false, //Enable stateful messages by default - can be changed at will to switch between stateless & stateful.
        'logger' => new Psr\Log\NullLogger()
		//'logger' => new vendor\psr\log\Psr\Log\NullLogger()
    ],
    'requestCreatorParams' => [
        'receivedFrom' => 'my test project' // The "Received From" string that will be visible in PNR History
    ]
]);

$client = new Client($params);
//echo "<pre>"; print_r($client); echo "</pre>";
//start code for travelboardsearch
	$opt = new FareMasterPricerTbSearch([
        'nrOfRequestedResults' => 30, //no of result get from the response
        'nrOfRequestedPassengers' => 2, //total no of passengers i.e., adults+childs+infants
        'passengers' => [				//passengers details array
            new MPPassenger([
                'type' => MPPassenger::TYPE_ADULT,
                'count' => 1
            ]),
            new MPPassenger([
                'type' => MPPassenger::TYPE_CHILD,
                'count' => 1
            ]),
        ],
        'itinerary' => [
            new MPItinerary([
                'departureLocation' => new MPLocation(['city' => 'DEL']), //from departure location
                'arrivalLocation' => new MPLocation(['city' => 'BOM']),   //to arrivalLocation
                'date' => new MPDate([
                    'dateTime' => new \DateTime('2017-08-28T10:00:00+0000', new \DateTimeZone('UTC')), //departure date
                    'timeWindow' => 5,
                    'rangeMode' => MPDate::RANGEMODE_MINUS_PLUS,
                    'range' => 1
                ])
            ]),
            ]
    ]);
	$Fare_TravelBoardSearch=$client->fareMasterPricerTravelBoardSearch(
		$opt
	);

	echo "<textarea>";print_r($Fare_TravelBoardSearch); echo "</textarea>";die;
    
	die;
Please check my request and give your valuable suggestion.

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-17 08:07
`Could not connect to host` is an error from a lower level and indicates a network problem. Have you tried if you're able to ping or otherwise reach the SOAP server mentioned in the WSDL?

This seems like the same error you've had [before](https://github.com/amabnl/amadeus-ws-client/issues/85#issuecomment-317490278). I really suggest you check out your network connectivity to the Amadeus WS server and try to fix this problem together with Amadeus Support.

I can't help you with that I'm afraid.

**Comment by JustBeDigital** [comment] 2017-08-17 16:05
Hi DerMika,

I have dowload aunch Amadeus pinger from https://webservices.amadeus.com/extranet/spinger.do
and run it in our network PC.
please check screen shot 
![Uploading Screenshot 2017-08-17 21.29.27.png…]()

after it I have check at our server.
please check the screenshot
![screenshot 2017-08-17 21 33 00](https://user-images.githubusercontent.com/30349487/29421804-cd8f6966-8393-11e7-8bcb-568402381b98.png)

I am waiting your valuable feedback.

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-17 16:27
I can't help you with that. You need to take this up with Amadeus.

**Comment by JustBeDigital** [comment] 2017-08-17 16:55
Hi DerMika,
our details are working fine in our core php code.
authetication,request and response  are  coming well in our core php code with these details.
But I want to use your amadeus-ws-client.
Because amadeus-ws-client is the best and structured solution.
can you please help me.
please check request and response which are coming with our core php code.

[AirFlight_Fare_MasterTBSearchReq.txt](https://github.com/amabnl/amadeus-ws-client/files/1232019/AirFlight_Fare_MasterTBSearchReq.txt)
[AirFlight_Fare_MasterTBSearchRes.txt](https://github.com/amabnl/amadeus-ws-client/files/1232020/AirFlight_Fare_MasterTBSearchRes.txt)

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-17 17:36
Ok, upon reviewing your sample code, there's one more thing I can think of. Try making the location to the WSDL file an absolute path. 

For example, in Symfony you can make a path from the root of the application using code like this: 

```php
'wsdl' => realpath(
    $this->get('kernel')->getRootDir() .
    DIRECTORY_SEPARATOR . "wsdl" . DIRECTORY_SEPARATOR . '1ASIWSMLLVN_PDT_20170724_131430.wsdl'
 );
```

At least that's how I do it in my code.

**Comment by JustBeDigital** [comment] 2017-08-18 16:17
Hi DerMika,
There is not WSDL File missing problem.
if WDL file is not found.
**it gives error like below mentioned.**
"Fatal error: Uncaught exception 'Amadeus\Client\InvalidMessageException' with message 'Message "Fare_MasterPricerTravelBoardSearch" is not in WDSL' in /opt/lampp/htdocs/amadeus-ws-client-master/src/Amadeus/Client/RequestCreator/Base.php:108 Stack trace: #0 /opt/lampp/htdocs/amadeus-ws-client-master/src/Amadeus/Client/RequestCreator/Base.php(88): Amadeus\Client\RequestCreator\Base->checkMessageIsInWsdl('Fare_MasterPric...') #1 /opt/lampp/htdocs/amadeus-ws-client-master/src/Amadeus/Client.php(1137): Amadeus\Client\RequestCreator\Base->createRequest('Fare_MasterPric...', Object(Amadeus\Client\RequestOptions\FareMasterPricerTbSearch)) #2 /opt/lampp/htdocs/amadeus-ws-client-master/src/Amadeus/Client.php(476): Amadeus\Client->callMessage('Fare_MasterPric...', Object(Amadeus\Client\RequestOptions\FareMasterPricerTbSearch), Array) #3 /opt/lampp/htdocs/amadeus-ws-client-master/my_try.php(82): Amadeus\Client->fareMasterPricerTravelBoardSearch(Object(Amadeus\Client\RequestOptions\FareMasterPricerTbSearch)) #4 {main} thrown in /opt/lampp/htdocs/amadeus-ws-client-master/src/Amadeus/Client/RequestCreator/Base.php on line 108"

it is giving response.
please check attached file and start reading from
[messagesAndVersions:protected] => Array
                (
                    [Air_RebookAirSegment] => Array
                        (
                            [version] => 14.1
                            [wsdl] => e5096fb9
                        )

                    [Air_SellFromRecommendation] => Array
                        (
                            [version] => 5.2
                            [wsdl] => e5096fb9
                        )

because all above values are coming from my WSDL.
[Response.txt](https://github.com/amabnl/amadeus-ws-client/files/1234951/Response.txt)

please help us on this so that we can take profit from amadeus-ws-client.
I have search alot on internet but not found such excellent and structured library for amadeus like amadeus-ws-client. 

Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-18 18:42
Yes, good point. 

The only thing left that I can do is try to reproduce the problem. For that you'd need to send me the WSDL and auth details *privately*. dieter (at) dermika (dot) be

**Comment by JustBeDigital** [comment] 2017-08-18 20:39
Hi DerMika
Thanks you so much for your Great support.
I have send please check you inbox.
I am waiting for your valuable feedback.
Regards,
-Kunwar Ali

**Comment by DerMika** [comment] 2017-08-19 16:11
I just checked your mail, and as I replied, the script you provided me works just fine. 

I get a proper `Fare_MasterPricerTravelBoardSearchReply` as I would expect. 

As I explained to you, either it's a network problem or there is some kind of problem with the SSL handshake. Please check if you can upgrade your PHP installation and/or your OpenSSL.

**Comment by DerMika** [comment] 2017-08-25 06:49
Do you have a status update? Did you manage to fix the problem?

**Comment by DerMika** [comment] 2017-09-01 15:52
Closing due to no feedback. Re-open if necessary!

**Closed by DerMika** 2017-09-01 15:52 UTC
Labels: question, waiting for feedback

**Comment by XYNOMEX** [comment] 2018-07-04 09:12
@DerMika Hey I have the same issue, so I'm wondering if there is any link I can ping to check if I can go through?

**Comment by DerMika** [comment] 2018-07-04 09:16
Which issue exactly? Many issues have been mentioned in this thread ;)
