### ISSUE TITLE
Missing value for Secure Flight(s)

### ISSUE THREAD

**Issue by tommiehansen** [amabnl/amadeus-ws-client#29] opened 2016-11-04 15:54 UTC
In order to check for secure flights in MasterPricer Amadeus should return a value of 'S' if it is true that a current flight requires what is commonly called 'Secure Flight data'. 

However it doesn't seem this library returns this data?

It's usually found within the array flightInformation;
flightInformation->addProductDetail->flightCharacteristic.

Is there some extra key/val one need to make in the request to get that data in the response?

Response arr example, STO-NYC: http://pasted.co/a4748626

**Comment by DerMika** [comment] 2016-11-04 17:06
Hi, 

I'm not familiar with all the peculiarities of the MasterPricer call, but this is an feature that I don't know the details of. I also didn't find any reference or example in the userguide of the `Fare_MasterPricerTravelBoardSearch` message. 

I do know that many options of how MasterPricer behaves are settings that are configurable on the Amadeus Office ID where the MasterPricer call is executed. 

So either this is a webservice option that I'm not familiar with, or it's because of some Office ID setting - at least that's my guess.

I suggest you contact Amadeus and have them investigate why this expected value is not in the response. They should be able to tell you the cause. If they tell you that you need to send a specific message to trigger this, provide me a sample, and I'll implement it in the library.

**Comment by tommiehansen** [comment] 2016-11-04 19:37
Thank you for the quick response! Will update with further response(s). I suspect that it might be an Office ID setting as you say (the whole config @ Amadeus user/office_id is basically a book worth of contents in itself). :)

**Comment by DerMika** [comment] 2016-11-22 08:40
If the response takes such a long time I suggest you contact your Amadeus support until they give you an answer with the status, and ask them to escalate the case.

**Comment by tommiehansen** [comment] 2016-11-22 09:49
As i wrote i've done this and yes, they've escalated the case.

**Comment by tommiehansen** [comment] 2016-12-06 20:31
Actually still awaiting feedback regarding this issue(!)

You don't happend to have anyone you could just ask? The problem and the array in the initial description is well documented within the MasterPricer documentation on the private extranet site, here's a screen:  
http://i.imgur.com/mWPyHx5.png

The problem being that we do not get that array neither using your lib or using custom libs. It's sort of an OfficeID/global setting of some kind. Those exist within the Amadeus system and is pretty tricky to really understand since some of these settings are undocumented and cannot just be overwritten using modified requests with special keys.

The reason this is of importance mostly have to do with the modified DOCS one has to send later on when something is labeled as being a 'Secure Flight'. It also enables one to omit non-needed customer information on non-secure flights like DOB (Date of Birth) for adults etc. One could of course write ugly code that just checks the segments for flights to or via a destination that _usually_ is labeled as 'Secure' but that could become a quite unreliable hack and could cause problems in the future.

**Comment by DerMika** [comment] 2016-12-06 20:45
I understand. If you know the case number assigned to your problem (PTR number?) I might try to escalate, but I can't promise anything. As I'm not officially involved in customer relations with you, I won't have much chance to put any pressure on anyone, except informally encourage them... (preferrably send this by e-mail, not here)

Also, if you have some kind of masterpricer request where you expect to see those 'secure flight' markers, please send me an example. I may try to reproduce it here, when I have the time.

**Comment by tommiehansen** [comment] 2016-12-06 21:04
Yeah, i figured as much. But good anyway. :)

#### Search data
```
STO-NYC, NON-STOP, 2 adults, 0 child, 0 infant
2017-02-04 - 2017-02-11 (return flight)
```

#### REQ/RESP
XML REQ: http://pastie.org/private/1tchysrqwjhjuboogopzoa
XML RESP: http://pastie.org/private/4ttqoujuhxz9fgjafln1gg

#### AM case number
4472839694

**Comment by tommiehansen** [comment] 2016-12-26 16:29
So this oddly enough has been solved 'auto-magically' at the moment, but waiting to hear what exactly Amadeus changed or did.

**Comment by bimusiek** [comment] 2017-02-17 08:57
@tommiehansen I will just leave comment here for future devs looking into this issue. :)
You need to know about Secure Flight Passenger Data (SFPD) only when creating PNR to add `DOCS` entry. 
You can do it after `AirSellFromRecommendation` call with `PNR_Retrieve` (or `AddMultiElements` if you add passengers and point of contact) by checking response of this calls ans searching for `statusIndicator` list. 

If it is secure flight it will have `SFP` in indicators. 👍

**Comment by DerMika** [comment] 2017-02-17 09:44
So @tommiehansen, I'm going to close this one as it doesn't look like a problem in this library. 

If that turns out to be wrong, we can still reopen this issue.

**Closed by DerMika** 2017-02-17 09:44 UTC
Labels: amadeus support, question, waiting for feedback

**Comment by tommiehansen** [comment] 2017-02-17 10:59
@bimusiek True, but in a normal 'search and book' -flow one usually want to know if secure or not before the user reaches the part where it need to fill in details so that one can add the extra fields needed like date of birth etc (and exclude not needed data input if not).

I don't know why I didn't update this thread before, but the solution to this specific problem is that Amadeus support need to fix ones office ID/it's an Amadeus bug that one can't control. If one mentions the specific arrays as I did they will be able to fix it.... in time. Often it's more about not getting in contact with the tech-people directly but rather having to deal with general support (varies per country).

When it works one do get the necessary data at flightInformation->addProductDetail->flightCharacteristic which make the process at later stages very simple using basic conditions.

@DerMika Yes, good as a reference though since this specific problem can cause some annoyances for a standard 'search and book' -flow.

_Sorry for any terrible language, writing this from my tablet in Isla Mujeres, Mexico at 6 in the morning_. ☺
