### ISSUE TITLE
flight Baggage and rules

### ISSUE THREAD

**Issue by ahmedeltokhy** [amabnl/amadeus-ws-client#145] opened 2018-02-12 11:57 UTC
Hello All,
Hope you are doing well, I want to retrieve the baggage of the flight and the refundability status.
could you tell me where to find these information

**Comment by DerMika** [comment] 2018-02-14 10:10
Hi, do you mean in the `Fare_MasterPricerTravelBoardSearchReply`?

In the Extranet, there is a mentioning of a "Free baggage allowance" option which can be configured on your office ID, which, if enabled, should provide you with the free baggage allowance per MasterPricer recommendation. 

I suggest you ask Amadeus Support if they can activate this setting on your Office, and they should also be able to tell you where you'll find this information in the `Fare_MasterPricerTravelBoardSearchReply`.

**Comment by andreigogu** [comment] 2018-02-16 09:16
Hi ahmedeltokhy,

check Fare_MasterPricerTravelBoardSearch version, it should be minimum 14.3
also add 
`'feeIds' => [
                    new MPFeeId(['type' => 'FBA', 'number' => 1]),
            ]`
in FareMasterPricerTbSearch

**Comment by DerMika** [comment] 2018-03-18 07:43
@ahmedeltokhy Is this issue solved now? If so, can you please close it?

**Comment by DerMika** [comment] 2018-03-31 08:50
Closing due to lack of feedback - you can re-open it if needed.

**Closed by DerMika** 2018-03-31 08:50 UTC
Labels: amadeus support, question, waiting for feedback

**Comment by mhrahul** [comment] 2018-05-21 11:19
@DerMika I have got the baggage info but can't understand what is the preferred airline?

`"freeBagAllowanceGrp": [
            {
                "freeBagAllownceInfo": {
                    "baggageDetails": {
                        "freeAllowance": 20,
                        "quantityCode": "W",
                        "unitQualifier": "K"
                    }
                },
                "itemNumberInfo": {
                    "itemNumberDetails": {
                        "number": 1
                    }
                }
            },`

I have used Fare_MasterPricerTravelBoardSearchReply &

`'flightOptions' => [
                    FareMasterPricerTbSearch::FLIGHTOPT_PUBLISHED,
                    FareMasterPricerTbSearch::FLIGHTOPT_UNIFARES,
                    'TAC',
                ],`

**Comment by DerMika** [comment] 2018-05-22 07:53
I assume that is the airline returned in the given recommendation?? You'll usually have a marketing carrier and possibly an operating carrier. I assume you'll need to use the marketing carrier.

**Comment by mhrahul** [comment] 2018-05-22 08:04
Well I have the marketing carrier. But the problem is the baggage information is coming on  
`"serviceFeesGrp": {
        "serviceTypeInfo": {
            "carrierFeeDetails": {
                "type": "FBA"
            }
        },
        "serviceCoverageInfoGrp": {
            "itemNumberInfo": {
                "itemNumber": {
                    "number": "1"
                }
            },
            "serviceCovInfoGrp": {
                "paxRefInfo": {
                    "travellerDetails": {
                        "referenceNumber": "1"
                    }
                },
                "coveragePerFlightsInfo": {
                    "numberOfItemsDetails": {
                        "referenceQualifier": "RS",
                        "refNum": "1"
                    },
                    "lastItemsDetails": {
                        "refOfLeg": "1"
                    }
                },
                "refInfo": {
                    "referencingDetail": {
                        "refQualifier": "F",
                        "refNumber": 1
                    }
                }
            }
        },
        "globalMessageMarker": [],
        "freeBagAllowanceGrp": {
            "freeBagAllownceInfo": {
                "baggageDetails": {
                    "freeAllowance": 20,
                    "quantityCode": "W",
                    "unitQualifier": "K"
                }
            },
            "itemNumberInfo": {
                "itemNumberDetails": {
                    "number": 1
                }
            }
        }
    }`

this array. I can't connect it with the flights. The flight recommendation array gives me the segmentFlightRef['referencingDetail']. But baggage info array has no connection with it.

**Comment by alaskaenterprises** [comment] 2020-03-05 08:54
Hello,
any update on this I'm not getting serviceFeesGrp in fareMasterPricerCalendar can anybody let me know whats the reason why I'm not getting this data in this API call?

**Comment by MetaiR** [comment] 2020-04-07 18:12
@mhrahul hi, could you find any connection? I have the exact same issue with my implementation

**Comment by mhrahul** [comment] 2020-04-09 05:22
@MetaiR can you please give a screenshot of your problem?

**Comment by Gaurav191** [comment] 2020-09-01 18:13
@MetaiR @mhrahul 

Yes every recommendation has connection with baggage. Please refer the screenshot. Hope this will help many others who are trying to achieve this.
<img width="695" alt="Capture" src="https://user-images.githubusercontent.com/12510874/91890224-c7de8300-ecac-11ea-84ff-26e85ae54bba.PNG">

**Comment by MetaiR** [comment] 2020-09-01 19:24
@Gaurav191 
wow, it is very helpful and I would be much more thankful if you send an example of a flight with multiple segments
