### ISSUE TITLE
GETTING EMPTY SESSION ARRAY WHEN PNR_RETRIEVE CALL FAILED

### ISSUE THREAD

**Issue by dil-hf** [amabnl/amadeus-ws-client#429] opened 2021-02-16 11:48 UTC
Hi,

Is it normal to have an empty array session when  PNR-Retrieve fails?
Whenever it failed, getSessionData() is empty.

@bimusiek @DerMika

**Comment by DerMika** [comment] 2021-02-16 12:06
You should configure the Request & Response logging https://github.com/amabnl/amadeus-ws-client/blob/master/docs/how-to.rst#logging-request-and-response to find out in detail what goes wrong.

Also, is this a duplicate of #428 ?

**Comment by DerMika** [comment] 2021-02-16 12:58
The response to your PNR_Retrieve on line 61 of your logfile contains session data and has `TransactionStatusCode="InSeries"`. If you check your `$client->getSessionData();` after receiving this response, you should get session info.

Something must be happening to the state of `$client` in the second between line 61 and 62 of your client... 

Also, lines 65-67 contain sensitive info, you may want to strip that.

**Comment by DerMika** [comment] 2021-02-16 13:10
Can you try running the client code with a debugger enabled?

Set a breakpoint at https://github.com/amabnl/amadeus-ws-client/blob/master/src/Amadeus/Client/Session/Handler/SoapHeader4.php#L209 and step through this function and see if it picks up the session info when handling the response of the PNR_Retrieve.

If it picks that up, the problem is the state of $client in your code. If it doesn't, it may be a bug or an incompatibility with your WSAP.

**Comment by dil-hf** [comment] 2021-02-16 15:59
Thank you @DerMika for your time.

I debug and find out that when PNR_retrieve failed (I mean with wrong PNR), the function getSessionDataFromHeader() is never called but it's being called when PNR_retrieve succeed.
is it normal?

**Comment by dil-hf** [comment] 2021-02-18 09:30
Hi @DerMika 

Can you guide me on how to get session info so that I can make a raw request as a workaround for avoiding losing the Amadeus slot?
Actually, $client->getSessionData(); is empty when pnr_retrieve failed but it getting logged.
Security_SignOut() works great when pnr_retrieve succeed.

Did anyone encounter the same issue as I do? 
Exist any other workaround to close an active session after a failed call?

Thank you for your time.

**Comment by DerMika** [comment] 2021-02-18 11:25
I found the problem. A PR is on the way...

**Comment by dil-hf** [comment] 2021-02-18 11:34
Hi ,

I got it also. I made the modification locally.
I was preparing the PR.

**Comment by dil-hf** [comment] 2021-02-18 11:40
Only one line added, so can I send it?

**Comment by DerMika** [comment] 2021-02-18 12:05
Well, i already made it. But since you have it running locally, can you verify that the fix (https://github.com/amabnl/amadeus-ws-client/pull/430) actually solves your problem? If so I can merge it to master

**Comment by dil-hf** [comment] 2021-02-18 12:10
You can merge it, it's the same one I made locally.

**Closed** 2021-02-18 12:11 UTC

**Comment by DerMika** [comment] 2021-02-18 12:22
released v1.12.0 which includes this fix.

**Comment by dil-hf** [comment] 2021-02-18 12:24
Great, thank you
